[package]
name = "winit-featurepack"
version = "0.1.0"
authors = ["CrLF0710"]
edition = "2018"
license = "MIT/Apache2"

[dependencies]
winit = { git = "https://github.com/crlf0710/winit", branch = "stable"}
winapi = { version = "0.3", features = ["winuser"]}
